name: Download Manga
on:
  workflow_dispatch:

jobs:
  scrape-and-pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 curl-cffi

      # The "-u" flag forces Python to print logs immediately in real-time
      - name: Run Scraper
        run: python -u scraper.py

      - name: Upload Master ZIP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Lookism-Chapters
          path: "CBZ_Files/"
          retention-days: 7
